<?php
/**
 * Created by PhpStorm.
 * User: dima
 * Date: 19.03.2017
 * Time: 19:49
 */

namespace phptools\PgSqlOrm\db;


use phptools\PgSqlOrm\db\types\AbstractType;
use phptools\PgSqlOrm\exception\Exception;
use ToolsPhp\Types\collections\TCollection;

class TypesCollection extends TCollection
{
    /**
     * TypesCollection constructor.
     * @param array ...$args
     */
    public function __construct(...$args)
    {
        parent::__construct(AbstractType::class, $args[0]);
    }

    public function getByAlias(string $alias): ?AbstractType
    {
        foreach ($this as $obj) {
            if ($obj->getAlias() == $alias) {
                return $obj;
            }
        }

       return null;
    }

    /**
     * @return \SplObjectStorage|AbstractType[]
     */
    public function getIterator()
    {
        return parent::getIterator(); // TODO: Change the autogenerated stub
    }


}